src/objects/FacebookApp__c.object
<CustomObject>
    <fields>
        <fullName>clientSecret__c</fullName>
        <inlineHelpText>Also known as Application Secret</inlineHelpText>
        <label>clientSecret</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Facebook App</label>
    <nameField>
        <label>FacebookApp Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Facebook Apps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FacebookAppSecretController.cls
public with sharing class FacebookAppSecretController {
    private FacebookApp__c app;
    
    public FacebookAppSecretController(ApexPages.StandardController controller) {
        this.app = (FacebookApp__c)controller.getRecord();
    }   

    public String getSecret() {
        return null;
    }
    
    public void setSecret(String secret) {
        app.clientSecret__c = FacebookCrypto.encrypt(secret);
    }
}