src/objects/FacebookSession__c.object
<CustomObject>
    <fields>
        <fullName>Expiry__c</fullName>
        <label>Expiry</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <label>Facebook Session</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Session Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Facebook Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FacebookHousekeeping.cls
/**
 * @author Pat Patterson - ppatterson@salesforce.com
 */

global class FacebookHousekeeping implements Schedulable {
    global void execute(SchedulableContext sc) {
    	List<FacebookSession__c> sessions = 
    	   [select Id from FacebookSession__c where (Expiry__c < :DateTime.now())];
        delete sessions;
    }

  	public static testmethod void TestException() {
        Test.startTest();
		FacebookHousekeeping fbh = new FacebookHousekeeping();
		fbh.execute(null);
		List<FacebookSession__c> sessions = 
    	   [select Id from FacebookSession__c where (Expiry__c < :DateTime.now())];
    	System.assertEquals(sessions.size(), 0);
        Test.stopTest();
    }   
}